### PR TITLE
Add Docker, add alarm() watchdog

### PR DESCRIPTION
**Pull request by v0s**

### CODE REVIEW

**Comment by jfowl** [comment]
Hey there, thanks for this PR.
Jan, the original author, is currently not activly maintaining this bot anymore. I will try to do my best and review this in this week. Thanks so far for your work ;)

**Comment by jfowl** [comment]
Okay, this looks good so far from just looking at the changes.

@browny99 can you quickly skim them too?
Otherwise, I would merge them on sunday.

**Comment by v0s** [comment]
Perhaps should be tested if it still works on Windows, since there's no alarm() there

**Comment by jfowl** [comment]
Jan said it is okay, so here it is.

**Pull request merged**
