### PR TITLE
Major upgrade for 64-bit IDs in Telegram

### PR DESCRIPTION
**Pull request by v0s**
Revives groupagreebot after new 64-bit userids appeared. 

Also other commits from https://github.com/v0s/telegram-bot-groupagree/commits/dev might come in handy

### CODE REVIEW

**Comment by jfowl** [comment]
Thank you very much for your contribution! As you might have noticed, this project is quite abandoned. Maybe @browny99 will find the time to review this, but we have not touched GroupAgreeBot in a long time and consider it mostly dead.

**Comment by v0s** [comment]
I see! I can try hosting the official @groupagreebot with my build on my machine, if you guys want. 

I’ve been hosting my @ctfagreebot instance for 2.5 years now, and it seems pretty stable even after random people somehow discovering it and creating polls in strange languages :)

**Review by browny99 — APPROVED** [review]
Looks good :D

**Comment by browny99** [comment]
> I see! I can try hosting the official @groupagreebot with my build on my machine, if you guys want. 

I don't know if that's a good idea, groupagreebot is a real mess and will deadlock on you 100% when you start to get timeouts/rate limits from telegram.
If Telegram changed their api to a point where it's usable again, maybe I'll start maintaining it again but afaik that's not the case. If there are too many requests to your bot it will not be able to answer all of them and my workaround for that is very complicated and also broken.

I'll look into it but for now I don't think that is feasible.

**Comment by v0s** [comment]
I would also try a local instance of https://github.com/tdlib/telegram-bot-api, maybe it‘s a cheap way to overcome the limits without refactoring the bot itself. 

Do you have an idea at what load did the bot break for you?

**Pull request merged**
